import Papa from "papaparse";

/**
 * Parses a CSV file and converts it into an array of transaction objects.
 * @param {File} file The CSV file to import.
 * @returns {Promise<Array<object>>} A promise that resolves with the array of transactions.
 */
export const importFromCSV = (file) => {
  return new Promise((resolve, reject) => {
    Papa.parse(file, {
      header: true, // Assumes the first row is headers (e.g., "Nội dung", "Số tiền")
      skipEmptyLines: true,
      complete: (results) => {
        if (results.errors.length) {
          reject(
            new Error("Lỗi khi đọc file CSV: " + results.errors[0].message)
          );
          return;
        }

        try {
          const transactions = results.data.map((row) => {
            const amount = parseFloat(row["Số tiền"]);
            // Validate required fields
            if (!row["Nội dung"] || isNaN(amount)) {
              throw new Error(
                `Dòng không hợp lệ trong file CSV: ${JSON.stringify(row)}`
              );
            }

            // We don't import ID and Date, they will be generated by Firestore
            return {
              text: row["Nội dung"],
              amount: amount,
              category: row["Hạng mục"] || null,
            };
          });
          resolve(transactions);
        } catch (error) {
          reject(error);
        }
      },
      error: (error) => {
        reject(new Error("Không thể đọc file: " + error.message));
      },
    });
  });
};
